Ext.define('Admin.modules.hotel.Model', {
    extend: 'Admin.generic.data.Model',
    proxy: {
        type: 'rest',
        url: 'admin/hotel',
        reader: Ext.create('Admin.generic.data.reader.JsonOne')
    },
    fields: [
        {label: 'ID', name: 'id', type: 'int', useNull: true, persist: false},
        {label: 'Name', name: 'name', type: 'string', persist: false},
        {label: 'Address', name: 'address', type: 'string', persist: false},
        {label: 'Country', name: 'country', type: 'string', persist: false},
        {label: 'City', name: 'city', type: 'string', persist: false},
        {label: 'HotelId', name: 'hotelId', type: 'string', persist: false},
        {label: 'Hotel', name: 'hotel', type: 'auto'},
        {label: 'Hotel', name: 'hotel', type: 'auto'},
        {label: 'Extranet', name: 'extranet', type: 'boolean', defaultValue: false, persist: false},
        {label: 'Currency', name: 'currency', type: 'auto'},
        {label: 'lcode', name: 'lcode', type: 'string', persist: false},
        {label: 'wuName', name: 'wuName', type: 'string', persist: false},
        {label: 'timeZone', name: 'timeZone', type: 'string', persist: false},
        {label: 'User', name: 'user', type: 'auto'},
        {label: 'Info', name: 'info', type: 'auto', persist: false},
        {name: 'checkIn', type: 'auto', persist: false},
        {name: 'checkOut', type: 'auto', persist: false},
        {name: 'earlyCheckIn', type: 'auto', persist: false},
        {name: 'lateCheckOut', type: 'auto', persist: false},
        {name: 'postAddress', type: 'auto', persist: false},
        {name: 'index', type: 'auto', persist: false},
        {name: 'officialAddress', type: 'auto', persist: false},
        {name: 'bookPhone', type: 'auto', persist: false},
        {name: 'accountPhone', type: 'auto', persist: false},
        {name: 'infoPhone', type: 'auto', persist: false},
        {name: 'email', type: 'auto', persist: false},
        {name: 'multiplier', type: 'auto', persist: false},
        {name: 'maxRooms', type: 'auto', persist: false},
        {name: 'description', type: 'auto', persist: false},
        {name: 'webSite', type: 'auto', persist: false},
        {name: 'tourismTax', type: 'auto', persist: false},
        {name: 'earlyCheckInNoBreakfast', type: 'boolean', persist: false},
        {name: 'vat', type: 'int', persist: false},
        {name: 'createdDate', type: 'int', persist: false},
        {name: 'blocked', type: 'boolean', persist: false},
        {name: 'paidUntil', persist: false},
        {name: 'manager', persist: false},
        {name: 'supervisor', persist: false},
    ],
    setTitle: function () {
        return this.get('name')
    }
});
