Ext.define("Pms.modules.analytics.model.Analytics", {
    extend: "Ext.data.Model",

    fields: [
        'id',
        {name: 'date', type: 'UTCDate', serialize: Pms.serializeUTC},
        {name: 'total', type: 'int'},
        {name: 'FRONT_DESK', type: 'int'},
        {name: 'HOTEL_DE', type: 'int'},
        {name: 'BOOKING', type: 'int'},
        {name: 'EXPEDIA', type: 'int'},
        {name: 'ITWG', type: 'int'},
        {name: 'IN_ITALIA', type: 'int'},
        {name: 'HOTELS_COM', type: 'int'},
        {name: 'RESERVER_IT', type: 'int'},
        {name: 'ACCOMODATIONZ_COM', type: 'int'},
        {name: 'HOTEL_BEDS', type: 'int'},
        {name: 'VENERE_COM', type: 'int'},
        {name: 'HRS_COM', type: 'int'},
        {name: 'TRAVEL_EUROPE', type: 'int'},
        {name: 'ATRAPALO', type: 'int'},
        {name: 'BB_PLANET', type: 'int'},
        {name: 'SPLENDIA', type: 'int'},
        {name: 'ESCAPIO', type: 'int'},
        {name: 'AGODA', type: 'int'},
        {name: 'LASTMINUTE', type: 'int'},
        {name: 'TRAVELOCITY', type: 'int'},
        {name: 'SABRE', type: 'int'},
        {name: 'BUDGETPLACES', type: 'int'},
        {name: 'HOSTELS_CLUB', type: 'int'},
        {name: 'ORBITZ', type: 'int'},
        {name: 'BOOKING_BUTTON', type: 'int'},
        {name: 'LATE_ROOMS', type: 'int'},
        {name: 'MBE_TRAVEL', type: 'int'},
        {name: 'IN_TOSCANA', type: 'int'},
        {name: 'HOSTEL_WORLD', type: 'int'},
        {name: 'OSTROVOK', type: 'int'},
        {name: 'sum', type: 'int'},
        {name: 'quantity', type: 'int'},
        {name: 'source'},
        {name: 'percent'},
    ]
});

