var countries = [
    { abbr: "AU", country: "Австралия"},
    { abbr: "AT", country: "Австрия"},
    { abbr: "AZ", country: "Азербайджан"},
    { abbr: "AX", country: "Аландские острова"},
    { abbr: "AL", country: "Албания"},
    { abbr: "DZ", country: "Алжир"},
    { abbr: "VI", country: "Американские Виргинские острова"},
    { abbr: "AS", country: "Американское Самоа"},
    { abbr: "AO", country: "Ангола"},
    { abbr: "AI", country: "Ангуилла"},
    { abbr: "AD", country: "Андорра"},
    { abbr: "AQ", country: "Антарктика"},
    { abbr: "AG", country: "Антигуа и Барбуда"},
    { abbr: "AR", country: "Аргентина"},
    { abbr: "AM", country: "Армения"},
    { abbr: "AW", country: "Аруба"},
    { abbr: "AF", country: "Афганистан"},
    { abbr: "BS", country: "Багамские острова"},
    { abbr: "BD", country: "Бангладеш"},
    { abbr: "BB", country: "Барбадос"},
    { abbr: "BH", country: "Бахрейн"},
    { abbr: "BY", country: "Беларусь"},
    { abbr: "BZ", country: "Белиз"},
    { abbr: "BE", country: "Бельгия"},
    { abbr: "BJ", country: "Бенин"},
    { abbr: "BM", country: "Бермудские Острова"},
    { abbr: "BG", country: "Болгария"},
    { abbr: "BO", country: "Боливия"},
    { abbr: "BA", country: "Босния и Герцеговина"},
    { abbr: "BW", country: "Ботсвана"},
    { abbr: "BR", country: "Бразилия"},
    { abbr: "IO", country: "Британская территория в Индийском океане"},
    { abbr: "VG", country: "Британские Виргинские Острова"},
    { abbr: "BN", country: "Бруней Даруссалам"},
    { abbr: "BF", country: "Буркина Фасо"},
    { abbr: "BI", country: "Бурунди"},
    { abbr: "BT", country: "Бутан"},
    { abbr: "VU", country: "Вануату"},
    { abbr: "VA", country: "Ватикан"},
    { abbr: "GB", country: "Великобритания"},
    { abbr: "HU", country: "Венгрия"},
    { abbr: "VE", country: "Венесуэла"},
    { abbr: "UM", country: "Внешние малые острова (США)"},
    { abbr: "TL", country: "Восточный Тимор"},
    { abbr: "VN", country: "Вьетнам"},
    { abbr: "GA", country: "Габон"},
    { abbr: "HT", country: "Гаити"},
    { abbr: "GY", country: "Гайана"},
    { abbr: "GM", country: "Гамбия"},
    { abbr: "GH", country: "Гана"},
    { abbr: "GP", country: "Гваделупа"},
    { abbr: "GT", country: "Гватемала"},
    { abbr: "GN", country: "Гвинея"},
    { abbr: "GW", country: "Гвинея-Биссау"},
    { abbr: "DE", country: "Германия"},
    { abbr: "GG", country: "Гернси"},
    { abbr: "GI", country: "Гибралтар"},
    { abbr: "HN", country: "Гондурас"},
    { abbr: "HK", country: "Гонконг, Особый Административный Район Китая"},
    { abbr: "GD", country: "Гренада"},
    { abbr: "GL", country: "Гренландия"},
    { abbr: "GR", country: "Греция"},
    { abbr: "GE", country: "Грузия"},
    { abbr: "GU", country: "Гуам"},
    { abbr: "DK", country: "Дания"},
    { abbr: "CD", country: "Демократическая Республика Конго"},
    { abbr: "JE", country: "Джерси"},
    { abbr: "DJ", country: "Джибути"},
    { abbr: "DO", country: "Доминиканская Республика"},
    { abbr: "EG", country: "Египет"},
    { abbr: "ZM", country: "Замбия"},
    { abbr: "EH", country: "Западная Сахара"},
    { abbr: "ZW", country: "Зимбабве"},
    { abbr: "IL", country: "Израиль"},
    { abbr: "IN", country: "Индия"},
    { abbr: "ID", country: "Индонезия"},
    { abbr: "JO", country: "Иордания"},
    { abbr: "IQ", country: "Ирак"},
    { abbr: "IR", country: "Иран"},
    { abbr: "IE", country: "Ирландия"},
    { abbr: "IS", country: "Исландия"},
    { abbr: "ES", country: "Испания"},
    { abbr: "IT", country: "Италия"},
    { abbr: "YE", country: "Йемен"},
    { abbr: "KZ", country: "Казахстан"},
    { abbr: "KY", country: "Каймановы острова"},
    { abbr: "KH", country: "Камбоджа"},
    { abbr: "CM", country: "Камерун"},
    { abbr: "CA", country: "Канада"},
    { abbr: "QA", country: "Катар"},
    { abbr: "KE", country: "Кения"},
    { abbr: "CY", country: "Кипр"},
    { abbr: "KI", country: "Кирибати"},
    { abbr: "CN", country: "Китай"},
    { abbr: "CC", country: "Кокосовые острова"},
    { abbr: "CO", country: "Колумбия"},
    { abbr: "KM", country: "Коморские Острова"},
    { abbr: "CG", country: "Конго"},
    { abbr: "KP", country: "Корейская Народно-Демократическая Республика"},
    { abbr: "CR", country: "Коста-Рика"},
    { abbr: "CI", country: "Кот д’Ивуар"},
    { abbr: "CU", country: "Куба"},
    { abbr: "KW", country: "Кувейт"},
    { abbr: "KG", country: "Кыргызстан"},
    { abbr: "LA", country: "Лаос"},
    { abbr: "LV", country: "Латвия"},
    { abbr: "LS", country: "Лесото"},
    { abbr: "LR", country: "Либерия"},
    { abbr: "LB", country: "Ливан"},
    { abbr: "LY", country: "Ливия"},
    { abbr: "LT", country: "Литва"},
    { abbr: "LI", country: "Лихтенштейн"},
    { abbr: "LU", country: "Люксембург"},
    { abbr: "MU", country: "Маврикий"},
    { abbr: "MR", country: "Мавритания"},
    { abbr: "MG", country: "Мадагаскар"},
    { abbr: "YT", country: "Майотта"},
    { abbr: "MO", country: "Макао (особый административный район КНР)"},
    { abbr: "MK", country: "Македония"},
    { abbr: "MW", country: "Малави"},
    { abbr: "MY", country: "Малайзия"},
    { abbr: "ML", country: "Мали"},
    { abbr: "MV", country: "Мальдивы"},
    { abbr: "MT", country: "Мальта"},
    { abbr: "MA", country: "Марокко"},
    { abbr: "MQ", country: "Мартиник"},
    { abbr: "MH", country: "Маршалловы Острова"},
    { abbr: "MX", country: "Мексика"},
    { abbr: "MZ", country: "Мозамбик"},
    { abbr: "MD", country: "Молдова"},
    { abbr: "MC", country: "Монако"},
    { abbr: "MN", country: "Монголия"},
    { abbr: "MS", country: "Монсеррат"},
    { abbr: "MM", country: "Мьянма"},
    { abbr: "NA", country: "Намибия"},
    { abbr: "NR", country: "Науру"},
    { abbr: "ZZ", country: "Неизвестный или недействительный регион"},
    { abbr: "NP", country: "Непал"},
    { abbr: "NE", country: "Нигер"},
    { abbr: "NG", country: "Нигерия"},
    { abbr: "AN", country: "Нидерландские Антильские острова"},
    { abbr: "NL", country: "Нидерланды"},
    { abbr: "NI", country: "Никарагуа"},
    { abbr: "NU", country: "Ниуе"},
    { abbr: "NZ", country: "Новая Зеландия"},
    { abbr: "NC", country: "Новая Каледония"},
    { abbr: "NO", country: "Норвегия"},
    { abbr: "AE", country: "Объединенные Арабские Эмираты"},
    { abbr: "OM", country: "Оман"},
    { abbr: "BV", country: "Остров Буве"},
    { abbr: "DM", country: "Остров Доминика"},
    { abbr: "IM", country: "Остров Мэн"},
    { abbr: "NF", country: "Остров Норфолк"},
    { abbr: "CX", country: "Остров Рождества"},
    { abbr: "BL", country: "Остров Святого Бартоломея"},
    { abbr: "MF", country: "Остров Святого Мартина"},
    { abbr: "SH", country: "Остров Святой Елены"},
    { abbr: "CV", country: "Острова Зеленого Мыса"},
    { abbr: "CK", country: "Острова Кука"},
    { abbr: "TC", country: "Острова Тёркс и Кайкос"},
    { abbr: "HM", country: "Острова Херд и Макдональд"},
    { abbr: "PK", country: "Пакистан"},
    { abbr: "PW", country: "Палау"},
    { abbr: "PS", country: "Палестинская автономия"},
    { abbr: "PA", country: "Панама"},
    { abbr: "PG", country: "Папуа-Новая Гвинея"},
    { abbr: "PY", country: "Парагвай"},
    { abbr: "PE", country: "Перу"},
    { abbr: "PN", country: "Питкерн"},
    { abbr: "PL", country: "Польша"},
    { abbr: "PT", country: "Португалия"},
    { abbr: "PR", country: "Пуэрто-Рико"},
    { abbr: "KR", country: "Республика Корея"},
    { abbr: "RE", country: "Реюньон"},
    { abbr: "RU", country: "Россия"},
    { abbr: "RW", country: "Руанда"},
    { abbr: "RO", country: "Румыния"},
    { abbr: "US", country: "США"},
    { abbr: "SV", country: "Сальвадор"},
    { abbr: "WS", country: "Самоа"},
    { abbr: "SM", country: "Сан-Марино"},
    { abbr: "ST", country: "Сан-Томе и Принсипи"},
    { abbr: "SA", country: "Саудовская Аравия"},
    { abbr: "SZ", country: "Свазиленд"},
    { abbr: "SJ", country: "Свальбард и Ян-Майен"},
    { abbr: "MP", country: "Северные Марианские Острова"},
    { abbr: "SC", country: "Сейшельские Острова"},
    { abbr: "PM", country: "Сен-Пьер и Микелон"},
    { abbr: "SN", country: "Сенегал"},
    { abbr: "VC", country: "Сент-Винсент и Гренадины"},
    { abbr: "KN", country: "Сент-Киттс и Невис"},
    { abbr: "LC", country: "Сент-Люсия"},
    { abbr: "RS", country: "Сербия"},
    { abbr: "CS", country: "Сербия и Черногория"},
    { abbr: "SG", country: "Сингапур"},
    { abbr: "SY", country: "Сирийская Арабская Республика"},
    { abbr: "SK", country: "Словакия"},
    { abbr: "SI", country: "Словения"},
    { abbr: "SB", country: "Соломоновы Острова"},
    { abbr: "SO", country: "Сомали"},
    { abbr: "SD", country: "Судан"},
    { abbr: "SR", country: "Суринам"},
    { abbr: "SL", country: "Сьерра-Леоне"},
    { abbr: "TJ", country: "Таджикистан"},
    { abbr: "TH", country: "Таиланд"},
    { abbr: "TW", country: "Тайвань"},
    { abbr: "TZ", country: "Танзания"},
    { abbr: "TG", country: "Того"},
    { abbr: "TK", country: "Токелау"},
    { abbr: "TO", country: "Тонга"},
    { abbr: "TT", country: "Тринидад и Тобаго"},
    { abbr: "TV", country: "Тувалу"},
    { abbr: "TN", country: "Тунис"},
    { abbr: "TM", country: "Туркменистан"},
    { abbr: "TR", country: "Турция"},
    { abbr: "UG", country: "Уганда"},
    { abbr: "UZ", country: "Узбекистан"},
    { abbr: "UA", country: "Украина"},
    { abbr: "WF", country: "Уоллис и Футуна"},
    { abbr: "UY", country: "Уругвай"},
    { abbr: "FO", country: "Фарерские острова"},
    { abbr: "FM", country: "Федеративные Штаты Микронезии"},
    { abbr: "FJ", country: "Фиджи"},
    { abbr: "PH", country: "Филиппины"},
    { abbr: "FI", country: "Финляндия"},
    { abbr: "FK", country: "Фолклендские острова"},
    { abbr: "FR", country: "Франция"},
    { abbr: "GF", country: "Французская Гвиана"},
    { abbr: "PF", country: "Французская Полинезия"},
    { abbr: "TF", country: "Французские Южные Территории"},
    { abbr: "HR", country: "Хорватия"},
    { abbr: "CF", country: "Центрально-Африканская Республика"},
    { abbr: "TD", country: "Чад"},
    { abbr: "ME", country: "Черногория"},
    { abbr: "CZ", country: "Чешская республика"},
    { abbr: "CL", country: "Чили"},
    { abbr: "CH", country: "Швейцария"},
    { abbr: "SE", country: "Швеция"},
    { abbr: "LK", country: "Шри-Ланка"},
    { abbr: "EC", country: "Эквадор"},
    { abbr: "GQ", country: "Экваториальная Гвинея"},
    { abbr: "ER", country: "Эритрея"},
    { abbr: "EE", country: "Эстония"},
    { abbr: "ET", country: "Эфиопия"},
    { abbr: "ZA", country: "Южная Африка"},
    { abbr: "GS", country: "Южная Джорджия и Южные Сандвичевы Острова"},
    { abbr: "JM", country: "Ямайка"},
    { abbr: "JP", country: "Япония"}
];