CREATE OR REPLACE FUNCTION public.drop_tenant(tenantId TEXT)
  RETURNS TEXT AS $$
BEGIN
  EXECUTE FORMAT('DROP SCHEMA IF EXISTS %I CASCADE;', $1);
  RETURN $1;
END;
$$
LANGUAGE plpgsql
VOLATILE
COST 20;